import os
from snakemake.io import expand
from scripts.helpers.send_email import send_email

def txids_from_checkpoint_second_round(wildcards):
    """Return list of TxIDs from checkpoint output (cached)."""
    chk_output = checkpoints.filter_selected_TxIDs_second_round.get(
        assembly_code=wildcards.assembly_code,
        gencode_version=wildcards.gencode_version,
        tss_subset=wildcards.tss_subset,
        distance=wildcards.distance,
        min_CpG = wildcards.min_CpG,
        minCount_expr=wildcards.minCount_expr,
        minSamples_expr=wildcards.minSamples_expr,
        K_closest=wildcards.K_closest
    ).output[0]

    with open(chk_output) as f:
        return [x.strip() for x in f]

def txids_from_checkpoint_third_round(wildcards):
    """Return list of TxIDs from checkpoint output (cached)."""
    chk_output = checkpoints.filter_selected_TxIDs_third_round.get(
        assembly_code=wildcards.assembly_code,
        gencode_version=wildcards.gencode_version,
        tss_subset=wildcards.tss_subset,
        distance=wildcards.distance,
        min_CpG = wildcards.min_CpG,
        minCount_expr=wildcards.minCount_expr,
        minSamples_expr=wildcards.minSamples_expr,
        K_closest=wildcards.K_closest,
        sample_type=wildcards.sample_type,
        leftCount_beta=wildcards.leftCount_beta,
        rightCount_beta=wildcards.rightCount_beta,
        minSamples_beta=wildcards.minSamples_beta,
        minCov=wildcards.minCov

    ).output[0]

    with open(chk_output) as f:
        return [x.strip() for x in f]

def get_txid_unpack_topK(wildcards):
    txids = txids_from_checkpoint_second_round(wildcards)
    return expand(rules.unpack_topK.output[0], TxID=txids, **wildcards)

def get_txid_unpack_rse(wildcards):
    txids = txids_from_checkpoint_second_round(wildcards)
    return expand(rules.unpack_RSE.output[0], TxID=txids, **wildcards)

def get_txid_xgb_input(wildcards):
    txids = txids_from_checkpoint_second_round(wildcards)
    return expand(rules.xgb_input.output[0], TxID=txids, **wildcards)

####

def get_txid_heatmap_outputs(wildcards):
    txids = txids_from_checkpoint_third_round(wildcards)
    return expand(rules.generate_feature_heatmap.output, TxID=txids, **wildcards)

def get_txid_train_outputs(wildcards):
    txids = txids_from_checkpoint_third_round(wildcards)
    return expand(rules.train_models.output.plot_path, TxID=txids, **wildcards)

def get_txid_extract_CpGs(wildcards):
    txids = txids_from_checkpoint_third_round(wildcards)
    return expand(rules.extract_CpGs_from_output.output.coords, TxID=txids, **wildcards)

def get_txid_gtf(wildcards):
    txids = txids_from_checkpoint_third_round(wildcards)
    return expand(rules.get_TxID_specific_gtf.output, TxID=txids, **wildcards)

def get_txid_generate_tracks(wildcards):
    txids = txids_from_checkpoint_third_round(wildcards)
    return expand(rules.generate_genome_tracks.output, TxID=txids, **wildcards)

def get_txid_prepare_TSSs(wildcards):
    txids = txids_from_checkpoint_third_round(wildcards)
    return expand(rules.prepare_TSSs_to_plot_tracks.output, TxID=txids, **wildcards)

def get_txid_slop_TSSs(wildcards):
    txids = txids_from_checkpoint_third_round(wildcards)
    return expand(rules.slop_TSSs.output, TxID=txids, **wildcards)

def get_txid_ini(wildcards):
    txids = txids_from_checkpoint_third_round(wildcards)
    return expand(rules.generate_ini_file.output, TxID=txids, **wildcards)

def get_txid_plot_tracks(wildcards):
    txids = txids_from_checkpoint_third_round(wildcards)
    return expand(rules.plot_genome_tracks.output, TxID=txids, **wildcards)

def get_txid_corr_meth(wildcards):
    txids = txids_from_checkpoint_third_round(wildcards)
    return expand(rules.corr_meth_expr.output[0], TxID=txids, **wildcards)

def get_txid_process_corr(wildcards):
    txids = txids_from_checkpoint_third_round(wildcards)
    return expand(rules.process_corr_meth_expr.output[0], TxID=txids, **wildcards)

def get_txid_cluster_corr(wildcards):
    txids = txids_from_checkpoint_third_round(wildcards)
    return expand(rules.cluster_corr_meth_expr.output[0], TxID=txids, **wildcards)


include: "rules/filter_selected_TxIDs.smk"

include: "rules/get_gencode_annotation.smk"
include: "rules/get_TSSs.smk"
include: "rules/sort_TSSs.smk"
include: "rules/filter_TSSs.smk"

include: "rules/filter_counts.smk"

include: "rules/get_mappability.smk"
include: "rules/filter_mappability.smk"
include: "rules/filter_CpGs_by_mappability.smk"
include: "rules/sort_CpGs.smk"

include: "rules/get_K_closest_CpGs.smk"
include: "rules/unpack_topK.smk"

include: "rules/filter_selected_TxIDs_second_round.smk"
include: "rules/unpack_RSE.smk"
include: "rules/get_TxIDs_to_exclude.smk"
include: "rules/xgb_input.smk"

include: "rules/filter_selected_TxIDs_third_round.smk"

include: "rules/corr_meth_expr.smk"
include: "rules/aggregate_corr_meth_expr.smk"
include: "rules/process_corr_meth_expr.smk"
include: "rules/cluster_corr_meth_expr.smk"
include: "rules/aggregate_clusters.smk"

include: "rules/train_models.smk"

include: "rules/generate_feature_heatmap.smk"

include: "rules/aggregate_models_output.smk"
include: "rules/plot_models_output.smk"

include: "rules/get_chrom_sizes.smk"
include: "rules/clean_chrom_sizes.smk"

include: "rules/get_TxID_specific_gtf.smk"

include: "rules/extract_CpGs_from_output.smk"
include: "rules/generate_genome_tracks.smk"

include: "rules/prepare_TSSs_to_plot_tracks.smk"
include: "rules/slop_TSSs.smk"

include: "rules/generate_ini_file.smk"
include: "rules/plot_genome_tracks.smk"

include: "rules/garbage_collector.smk"

include: "rules/get_CpG_Tx_pairs.smk"
include: "rules/get_composite_coordinates.smk"
include: "rules/get_sel_feats_coordinates.smk"
include: "rules/get_pairs_with_coords.smk"
include: "rules/sort_pairs_with_coords.smk"
include: "rules/slop_pairs_with_coords.smk"
include: "rules/get_GRN.smk"

sender = config["sender"][0]
app_password = config["app_password"][0]
recipients = config["recipients"]

assembly_codes = config["assembly_codes"]
gencode_versions = config["gencode_versions"]
tss_subsets = config["tss_subsets"]
sample_types = config["sample_types"]
distances = config["distances"]
min_CpGs = config["min_CpGs"]
K_closests = config["K_closests"]
leftCount_betas = config["leftCount_betas"]
rightCount_betas = config["rightCount_betas"]
minCount_exprs = config["minCount_exprs"]
minSamples_betas = config["minSamples_betas"]
minCovs = config["minCovs"]
minSamples_exprs = config["minSamples_exprs"]
importances = config["importances"]
use_TMRs = config["use_TMRs"][0]
test_sizes = config["test_sizes"]
CVs = config["CVs"]

rule all:
    input:
        expand(
            "resources/checks/generate/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}",
                assembly_code=assembly_codes,
                gencode_version=gencode_versions,
                tss_subset=tss_subsets,
                distance=distances,
                min_CpG = min_CpGs,
                sample_type=sample_types,
                leftCount_beta = leftCount_betas,
                rightCount_beta = rightCount_betas,
                minSamples_beta = minSamples_betas,
                minCov = minCovs,
                minCount_expr=minCount_exprs,
                minSamples_expr=minSamples_exprs,
                K_closest=K_closests
        ),
        expand(
            "results/GRN/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}_{test_size}_{CV}",
                assembly_code=assembly_codes,
                gencode_version=gencode_versions,
                tss_subset=tss_subsets,
                distance=distances,
                min_CpG = min_CpGs,
                sample_type=sample_types,
                leftCount_beta = leftCount_betas,
                rightCount_beta = rightCount_betas,
                minSamples_beta = minSamples_betas,
                minCov = minCovs,
                minCount_expr=minCount_exprs,
                minSamples_expr=minSamples_exprs,
                K_closest=K_closests,
                test_size=test_sizes,
                CV=CVs
        ),
        expand(
            "results/corr_meth_expr/bed/clustered/aggr/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}_{test_size}_{CV}", 
                assembly_code=assembly_codes,
                gencode_version=gencode_versions,
                tss_subset=tss_subsets,
                distance=distances,
                min_CpG = min_CpGs,
                sample_type=sample_types,
                leftCount_beta = leftCount_betas,
                rightCount_beta = rightCount_betas,
                minSamples_beta = minSamples_betas,
                minCov = minCovs,
                minCount_expr=minCount_exprs,
                minSamples_expr=minSamples_exprs,
                K_closest=K_closests,
                test_size=test_sizes,
                CV=CVs
        ),
        expand(
            "results/checks/tracks/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}_{test_size}_{CV}_{importance}",
                assembly_code=assembly_codes,
                gencode_version=gencode_versions,
                tss_subset=tss_subsets,
                distance=distances,
                min_CpG = min_CpGs,
                sample_type=sample_types,
                leftCount_beta = leftCount_betas,
                rightCount_beta = rightCount_betas,
                minSamples_beta = minSamples_betas,
                minCov = minCovs,
                minCount_expr=minCount_exprs,
                minSamples_expr=minSamples_exprs,
                K_closest=K_closests,
                test_size=test_sizes,
                CV=CVs,
                importance=importances
        ),
        expand(
            "results/checks/heatmap/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}",
                assembly_code=assembly_codes,
                gencode_version=gencode_versions,
                tss_subset=tss_subsets,
                distance=distances,
                min_CpG = min_CpGs,
                sample_type=sample_types,
                leftCount_beta = leftCount_betas,
                rightCount_beta = rightCount_betas,
                minSamples_beta = minSamples_betas,
                minCov = minCovs,
                minCount_expr=minCount_exprs,
                minSamples_expr=minSamples_exprs,
                K_closest=K_closests
        ),
        expand(
            "results/plots/ML/hyper/density/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}_{test_size}_{CV}.pdf",
                assembly_code=assembly_codes,
                gencode_version=gencode_versions,
                tss_subset=tss_subsets,
                distance=distances,
                min_CpG = min_CpGs,
                sample_type=sample_types,
                leftCount_beta = leftCount_betas,
                rightCount_beta = rightCount_betas,
                minSamples_beta = minSamples_betas,
                minCov = minCovs,
                minCount_expr=minCount_exprs,
                minSamples_expr=minSamples_exprs,
                K_closest=K_closests,
                test_size=test_sizes,
                CV=CVs
        )

rule all_unpack_topK:
    input:
        get_txid_unpack_topK,
    output:
        all_done_txid="resources/CpG_data/top_K/checks/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}"
    shell:
        """
        echo {input} >> {output.all_done_txid}
        """

rule all_unpack_RSE:
    input:
        get_txid_unpack_rse,
    output:
        all_done_txid="data/checks/rse/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}"
    shell:
        """
        echo {input} >> {output.all_done_txid}
        """

rule all_xgb_inputs:
    input:
        get_txid_xgb_input,
    output:
        all_done_txid="data/checks/xgb/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}"
    shell:
        """
        echo {input} >> {output.all_done_txid}
        """

rule plot_all_heatmaps:
    input:
        get_txid_heatmap_outputs
    output:
        all_done_txid="results/checks/heatmap/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}"
    shell:
        """
        echo {input} >> {output.all_done_txid}
        """

rule run_all_models:
    input:
        get_txid_train_outputs
    output:
        all_done_txid="results/checks/train/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}_{test_size}_{CV}"
    shell:
        """
        echo {input} >> {output.all_done_txid}
        """

rule extract_all_CpGs:
    input:
        get_txid_extract_CpGs
    output:
        all_done_txid="results/checks/extract/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}_{test_size}_{CV}"
    shell:
        """
        echo {input} >> {output.all_done_txid}
        """

rule generate_all_gtfs:
    input:
        get_txid_gtf
    output:
        all_done_txid="resources/checks/generate/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}"
    shell:
        """
        echo {input} >> {output.all_done_txid}
        """

rule generate_all_tracks:
    input:
        get_txid_generate_tracks
    output:
        all_done_txid="results/checks/generate/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}_{test_size}_{CV}_{importance}"
    shell:
        """
        echo {input} >> {output.all_done_txid}
        """

rule prepare_all_TSSs:
    input:
        get_txid_prepare_TSSs
    output:
        all_done_txid="results/checks/prepare/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}_{test_size}_{CV}_{importance}"
    shell:
        """
        echo {input} >> {output.all_done_txid}
        """

rule slop_all_TSSs:
    input:
        get_txid_slop_TSSs
    output:
        all_done_txid="results/checks/slop/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}_{test_size}_{CV}_{importance}"
    shell:
        """
        echo {input} >> {output.all_done_txid}
        """

rule generate_all_inis:
    input:
        get_txid_ini
    output:
        all_done_txid="results/checks/ini/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}_{test_size}_{CV}_{importance}"
    shell:
        """
        echo {input} >> {output.all_done_txid}
        """

rule plot_all_tracks:
    input:
        get_txid_plot_tracks
    output:
        all_done_txid="results/checks/tracks/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}_{test_size}_{CV}_{importance}"
    shell:
        """
        echo {input} >> {output.all_done_txid}
        """

rule all_corr_meth:
    input:
        get_txid_corr_meth,
    output:
        all_done_txid="results/checks/corr_meth_expr/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}"
    shell:
        """
        echo {input} >> {output.all_done_txid}
        """

rule process_all_corr:
    input:
         get_txid_process_corr,
    output:
        all_done_txid="results/checks/corr/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}_{test_size}_{CV}"
    shell:
        """
        echo {input} >> {output.all_done_txid}
        """

rule cluster_all_corr:
    input:
         get_txid_cluster_corr,
    output:
        all_done_txid="results/checks/cluster/{assembly_code}_{sample_type}_{leftCount_beta}_{rightCount_beta}_{minSamples_beta}_{minCov}_v{gencode_version}_{tss_subset}_{distance}_{min_CpG}_{minCount_expr}_{minSamples_expr}_{K_closest}_{test_size}_{CV}"
    shell:
        """
        echo {input} >> {output.all_done_txid}
        """

wildcard_constraints:
    assembly_code="hg\\d{2}",
    gencode_version="[0-9]+",
    tss_subset="[a-z]+",
    distance = "[0-9]+",
    sample_type="[A-Z]",
    minCpG="[0-9]+",
    leftCount_beta="\\d+(\\.\\d+)?",
    rightCount_beta="\\d+(\\.\\d+)?",
    minSamples_beta = "[0-9]+",
    minCov = "[0-9]+",
    minCount_expr="[0-9]+",
    minSamples_expr="[0-9]+",
    importance="[a-z]+",
    K_closest="[0-9]+",
    CV="[0-9]+",
    test_size="\\d+(\\.\\d+)?"
